### ISSUE TITLE
encrypter doesn't work

### ISSUE THREAD

**Issue by gottembruh** [RudMike/RmEncrypter_PublicVersion#1]
bruh ur code is bullshit anyway

**Comment by gottembruh** [comment]
why u dont answer to me noob i've being waiting too long

**Comment by gottembruh** [comment]
bad support

**Comment by gottembruh** [comment]
lol

**Comment by RudMike** [comment]
The full version was available only for beta testing. Now it's over. You can buy the full version for only 999.99$

**Comment by gottembruh** [comment]
sukmadic man rly price is too high

**Comment by RudMike** [comment]
Don't worry, I can do special discount for you as a beggar. Your special price is 999.95$

**Comment by gottembruh** [comment]
I wouldn't give u even 1 penny for this crap 😎

**Comment by gottembruh** [comment]
Well I can give 0,25 penny if it exist

**Comment by RudMike** [comment]
For this price I can take a screenshot, think about it

**Comment by gottembruh** [comment]
Ok I agree now tell me your card number and cvv code

**Comment by RudMike** [comment]
I don't have a card. Send me the pictures of your card with all sides, the 3D model, your passport copy and git will make the payment in auto-mode
